# Site settings
title: CharCai's Blog
description: 'Work Harder, Hard Worker.'
keyword: CharCai, CharCai的博客
url: 'https://charcai.github.io' # your host
# if you don't need baseurl, you should leave this value blank.
baseurl: ''

# Navigation links
nav:
  home: '/'
  link: '/link.html'
  about: '/about.html'

# Footer
footer:
  since: 2018

# Author
author: 'CharCai'
nickname: 'CharCai'
bio: '专注OI && EDM'

avatar: 'https://charcai.github.io/apple-touch-icon.png'
# 'https://s1.ax1x.com/2018/08/23/PTookV.jpg'

# Amazing Counters
counter: true

# Search
search: true

# Night mode
nightMode: false

# Comments
comments:
  gitalk: false
  gitalk_clientID: '424ff8e90c566fb9f21f'
  gitalk_Secret: '3f9b6c296723c9631af887b9651eff5699eea9a2'
  gitalk_repo: 'Blog'
  gitalk_owner: '1481767320'
  gitalk_admin: 'charcai'
  pagerDirection: 'first'
# distractionFreeMode: false

# MathJax by Ray-Eldath
mathjax: false

# Share
social-share: true
social-share-items: ['qq', 'wechat', 'qzone', 'weibo', 'douban', 'facebook']

# theme color 
theme-color: 'default'  # pink or default

# Post header background patterns (when the post no cover): circuitBoard, overlappingCircles, food, glamorous, ticTacToe, seaOfClouds
postPatterns: 'circuitBoard'

# SNS settings 
# url: email, weibo, zhihu, twitter, instagram, juejin, github, douban, facebook, dribble, uicn, jianshu, medium, linkedin
sns:
  juejin: '//juejin.im/user/5b335c16f265da59780b926e'
  github: '//github.com/charcai'
  email: 'mailto:char_cai@outlook.com'
# Tags
recommend-tags: true # whether or not display recommend-tags on the sidebar
recommend-condition-size: 12 # a tag will be recommended if the size of it is more than this value

# Build settings
paginate: 6
paginate_path: 'page:num'
exclude: ['node_modules', 'dev', 'package.json', 'gulpfile.js', '.gitignore', 'README.md', 'update']
#safe: false;

# Markdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM

# RSS
RSS: true

# Permalink
# See: https://github.com/kaeyleo/jekyll-theme-H2O/issues/35
permalink: /:year/:month/:day/:title.html

# Plugins
plugins: [jekyll-paginate, jekyll-sitemap]
